## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=100G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.pySCENIC_SLE

cd autoimmune.datasets/lupus_Chun

mkdir -p SCENIC

### STEP 0: Convert Seurat object to loom ###
#conda activate Aim_1
#Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/SCENIC/convert.Seurat.R pbmc.female.control-managed.RDS

### STEP 1: Gene regulatory network inference, and generation of co-expression modules ###
# transcription factors list
conda activate pyscenic
f_tfs=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/allTFs_hg38.txt

pyscenic grn SCENIC/expr_matrix.csv $f_tfs -o SCENIC/adj.csv --num_workers 20

### STEP 2-3: Regulon prediction aka cisTarget from CLI ###
# ranking databases
f_db_names=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/cisTarget_databases/*feather
# motif databases
f_motif_path=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl

pyscenic ctx SCENIC/adj.csv \
    $f_db_names \
    --annotations_fname $f_motif_path \
    --expression_mtx_fname SCENIC/expr_matrix.csv \
    --output SCENIC/reg.csv \
    --mask_dropouts \
    --num_workers 20

### STEP 4: Cellular enrichment (aka AUCell) from CLI ###
pyscenic aucell \
    SCENIC/expr_matrix.csv \
    SCENIC/reg.csv \
    --output SCENIC/SCENIC.auc.csv \
    --num_workers 20

### AUC analysis ###
conda activate Aim_1
Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/SCENIC/AUC.analysis.R pbmc.female.control-managed.RDS