## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=20G
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.pySCENIC
#$ -t 1-4

study=(pSS_GSE157278 CD_Kong/colon CD_Kong/TI UC_GSE125527 MS_GSE193770) 

cd autoimmune.datasets/${study[${SGE_TASK_ID}-1]}

#mkdir -p SCENIC

### STEP 0: Convert Seurat object to loom ###
#conda activate Aim_1
#Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/SCENIC/convert.Seurat.R pbmc.female.RDS

### STEP 1: Gene regulatory network inference, and generation of co-expression modules ###
# transcription factors list
#conda activate pyscenic
#f_tfs=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/allTFs_hg38.txt

#pyscenic grn SCENIC/pbmc.female.loom $f_tfs -o SCENIC/adj.csv --num_workers 20

### STEP 2-3: Regulon prediction aka cisTarget from CLI ###
# ranking databases
#f_db_names=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/cisTarget_databases/*feather
# motif databases
#f_motif_path=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl

#pyscenic ctx SCENIC/adj.csv \
    #$f_db_names \
    #--annotations_fname $f_motif_path \
    #--expression_mtx_fname SCENIC/pbmc.female.loom \
    #--output SCENIC/reg.csv \
    #--mask_dropouts \
    #--num_workers 20

### STEP 4: Cellular enrichment (aka AUCell) from CLI ###
#pyscenic aucell \
    #SCENIC/pbmc.female.loom \
    #SCENIC/reg.csv \
    #--output SCENIC/SCENIC.auc.csv \
    #--num_workers 4

### AUC analysis ###
conda activate Aim_1
Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/SCENIC/AUC.analysis.R pbmc.female.RDS