## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=100G
#$ -l tmp_requested=100G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.pySCENIC
#$ -t 1:5

study=(MS_GSE193770 UC_GSE125527 CD_Kong/colon CD_Kong/TI lupus_Chun) 

cd autoimmune.datasets/${study[${SGE_TASK_ID}-1]}

mkdir -p SCENIC

### STEP 0: Convert Seurat object to loom ###
conda activate Aim_1
Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/SCENIC/convert.Seurat.R pbmc.female.RDS

conda activate pyscenic

### STEP 1: Gene regulatory network inference, and generation of co-expression modules ###
# transcription factors list
f_tfs=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/allTFs_hg38.txt

pyscenic grn SCENIC/pbmc.loom $f_tfs -o SCENIC/adj.csv --num_workers 20

### STEP 2-3: Regulon prediction aka cisTarget from CLI ###
# ranking databases
f_db_names=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/cisTarget_databases/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather
# motif databases
f_motif_path=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl

pyscenic ctx SCENIC/adj.csv \
    $f_db_names \
    --annotations_fname $f_motif_path \
    --expression_mtx_fname pbmc.loom \
    --output SCENIC/reg.csv \
    --mask_dropouts \
    --num_workers 20

### STEP 4: Cellular enrichment (aka AUCell) from CLI ###
pyscenic aucell \
    SCENIC/pbmc.loom \
    SCENIC/reg.csv \
    --output SCENIC/pbmc.female.SCENIC.loom \
    --num_workers 20