## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=50G
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ASE
#$ -t 1-10

conda activate Aim_2

id=$(sed -n ${SGE_TASK_ID}p datasets/OneK1k/female.ids.txt)
genome_fa=/directflow/SCCGGroupShare/projects/lacgra/genome.files/X.fa

echo $id

cd /directflow/SCCGGroupShare/projects/lacgra/ASEReadCounter/individuals/$id

ls *-?.bam > bam.list.txt

# # Freebayes on multiple files
# freebayes -f $genome_fa -F 0.2 -C 2 -L bam.list.txt > var.vcf

# Freebayes on single files
for file in *-?.bam; do freebayes -f $genome_fa -F 0.2 -C 2 -b $file > "${file%.*}".vcf; done

# Filter VCF for Qual > 20
for file in *-?.vcf; do vcffilter -f "QUAL > 20" $file > "${file%.*}".qual.vcf; done

# Create index for VCF
for file in *-?.vcf; do /directflow/SCCGGroupShare/projects/lacgra/tools/gatk-4.2.6.1/gatk IndexFeatureFile -I "${file%.*}".qual.vcf; done

# Run ASEReadCounter
for file in *-?.bam; do /directflow/SCCGGroupShare/projects/lacgra/tools/gatk-4.2.6.1/gatk ASEReadCounter -R $genome_fa -I $file --variant "${file%.*}".qual.vcf -O "${file%.*}".txt; done
