## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=100G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.DEG
#$ -t 1-5

conda activate Aim_1

study=(MS_GSE193770 pSS_GSE157278 UC_GSE125527 CD_Kong/colon CD_Kong/TI) 

cd autoimmune.datasets/${study[${SGE_TASK_ID}-1]}

Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/functions/differential.expression.R pbmc.female.RDS