## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=50G
#$ -pe smp 6
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.pSS
#$ -t 1:40

conda activate Aim_3

# Set study
#study=MS_GSE193770
#study=UC_GSE125527
#study=UC_GSE182270
#study=UC_JamesLab
study=pSS_GSE157278
#study=lupus_Chun

# Set working directory
cd autoimmune.datasets/$study

# Export expression matrices
#Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/R/Aim_3/export.expression.matrix.R pbmc.female.RDS

# Read in files
file=$(sed -n ${SGE_TASK_ID}p exp.matrix/file.list.txt)

echo $file

# Run Logit
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.regression.py $file
# Run RF
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/random.forest.py $file
# Run SVM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/support.vector.machine.py $file
# Run GBM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/gradient.boosting.machine.py $file
# Run MLP
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/multilayer.perceptron.py $file