## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=20G
#$ -l tmp_requested=20G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.SLE
#$ -t 1:66

conda activate Aim_3

# Set working directory
cd autoimmune.datasets/lupus_Chun

# Read in files
file=$(sed -n ${SGE_TASK_ID}p exp.matrix/file.list.txt)

echo $file

#echo split files and select features with Boruta
#python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/Boruta.py exp.matrix/$file
#echo Run Logit
#python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.regression.py exp.matrix/$file 
#echo Run RF
#python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/random.forest.py exp.matrix/$file 
#echo Run SVM
#python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/support.vector.machine.py exp.matrix/$file 
#echo Run GBM
#python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/gradient.boosting.machine.py exp.matrix/$file 
echo Run MLP
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/multilayer.perceptron.py exp.matrix/$file

echo Plot combined PR curves
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/plot.all.PRcurves.py exp.matrix/$file

echo voting classifier
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/voting.classifier.py exp.matrix/$file 