## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=8G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.analysis
#$ -t 1-46

conda activate Aim_3

cd /directflow/SCCGGroupShare/projects/lacgra/SLE


file=$(sed -n "${SGE_TASK_ID}p" FLARE/file.list.txt)

echo $file

for i in {1..10}; do
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/predict_FLARE.py $i $file
done