## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=8G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.analysis
#$ -t 1-37

conda activate Aim_3

cd /directflow/SCCGGroupShare/projects/lacgra/autoimmune.datasets/SLE_GSE135779


file=$(sed -n "${SGE_TASK_ID}p" predicting.list.txt)

echo $file

for i in {1..10}; do
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/predict_independent_SLE.py $i $file adult
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/predict_independent_SLE.py $i $file child
done