## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=100G
#$ -l tmp_requested=100G
#$ -pe smp 6
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.UC1
#$ -t 1:10

conda activate Aim_3

# Set study
study=MS_GSE193770
#study=UC_GSE125527
#study=UC_GSE182270
#study=pSS_GSE157278

cd autoimmune.datasets/$study

# Read in files
file=$(sed -n ${SGE_TASK_ID}p exp.matrix/file.list.txt)

echo $file

# Run Logit
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.regression.py $file
# Run RF
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/random.forest.py $file
# Run SVM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/support.vector.machine.py $file
# Run GBM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/gradient.boosting.machine.py $file
# Run MLP
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/multilayer.perceptron.py $file

# Extract Features
#python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/extract.features.py

# Combine metrics
#Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/R/Aim_3/ML.metrics.df.R