## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=20G
#$ -pe smp 16
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.analysis
#$ -t 1-2

conda activate Aim_3

filelines=(43 78)

# Set working directory
cd SLE

file=$(sed -n ${filelines[$((SGE_TASK_ID - 1))]}p pseudobulk/file.list.txt)

echo $file

# iterate over the 10 splits
for i in {7..10}; do

    echo split files and select features with Boruta and elesticnet
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/boruta_enet.py $file $i
    echo Run Logit
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/logit.regression.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/logit.regression.py $file $i combined
    echo Run RF
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/random.forest.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/random.forest.py $file $i combined
    echo Run SVM
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/support.vector.machine.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/support.vector.machine.py $file $i combined
    echo Run GBM
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/gradient.boosting.machine.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/gradient.boosting.machine.py $file $i combined
    echo Run MLP
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/multilayer.perceptron.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/multilayer.perceptron.py $file $i combined

    echo Plot combined PR curves
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/plot.all.PRcurves.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/plot.all.PRcurves.py $file $i combined

    echo voting classifier
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/voting.classifier.py $file $i intersection
    python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/voting.classifier.py $file $i combined

    echo done split_$i
done