## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=50G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.HVG.test

conda activate Aim_3

# Set study
# study=pSS_GSE157278 # 40 files
study=lupus_Chun # 44 files
# study=CD_Kong/colon # 44 files
# study=CD_Kong/TI # 50
#study=SSc_GSE138669 # ?
#study=T1D_parsebio # ?
#study=sarcoidosis_GSE132338 # ?

# Set working directory
cd autoimmune.datasets/$study

file=exp.matrix/Tcm.Naive.helper.T.cells.HVG.RDS

echo Run Logit
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.HVG.py $file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.HVG.py $file -random
echo Run RF
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/RF.HVG.py $file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/RF.HVG.py $file -random
echo Run SVM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SVM.HVG.py $file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SVM.HVG.py $file -random
echo Run GBM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/GBM.HVG.py $file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/GBM.HVG.py $file -random
echo Run MLP
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/MLP.HVG.py $file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/MLP.HVG.py $file -random