## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=8G
#$ -l tmp_requested=8G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.HVG.test
#$ -t 1-9

conda activate Aim_3

# Set study
# study=pSS_GSE157278 # 3
study=lupus_Chun # 10 files
# study=CD_Kong/colon # 5
# study=CD_Kong/TI # 
#study=SSc_GSE138669 # 
#study=T1D_parsebio # 
#study=sarcoidosis_GSE132338 # 

# Set working directory
cd autoimmune.datasets/$study

# SLE
files=(B.cells.HVG.RDS Cycling.T.cells.HVG.RDS Non.classical.monocytes.HVG.RDS \
Plasma.cells.HVG.RDS Plasmablasts.HVG.RDS Regulatory.T.cells.HVG.RDS  \
Tem.Effector.helper.T.cells.HVG.RDS. Tem.Temra.cytotoxic.T.cells.HVG.RDS Tem.Trm.cytotoxic.T.cells.HVG.RDS)
file=${files[$SGE_TASK_ID-1]}

# pSS
#files=(Regulatory.T.cells.HVG.RDS Tcm.Naive.helper.T.cells.HVG.RDS Tem.Temra.cytotoxic.T.cells.HVG.RDS)
#file=${files[$SGE_TASK_ID-1]}

# CD Kong colon
#files=(CD16..NK.cells.HVG.RDS Tem.Effector.helper.T.cells.HVG.RDS \
#Tem.Trm.cytotoxic.T.cells.HVG.RDS Trm.cytotoxic.T.cells.HVG.RDS \
#Type.17.helper.T.cells.HVG.RDS)
#file=${files[$SGE_TASK_ID-1]}

echo Run Logit
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.HVG.py exp.matrix/$file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/logit.HVG.py exp.matrix/$file -random
echo Run RF
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/RF.HVG.py exp.matrix/$file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/RF.HVG.py exp.matrix/$file -random
echo Run SVM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SVM.HVG.py exp.matrix/$file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SVM.HVG.py exp.matrix/$file -random
echo Run GBM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/GBM.HVG.py exp.matrix/$file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/GBM.HVG.py exp.matrix/$file -random
echo Run MLP
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/MLP.HVG.py exp.matrix/$file -X
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/MLP.HVG.py exp.matrix/$file -random