## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q long.q
#$ -r yes
#$ -l mem_requested=50G
#$ -pe smp 16
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.analysis
#$ -t 1-10

conda activate Aim_3

# Set working directory
cd SLE

file=$(sed -n 2p pseudobulk/file.list.txt)

echo $file

echo split files and select features with Boruta and elesticnet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/boruta_enet.py $file $SGE_TASK_ID
echo Run Logit
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/logit.regression.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/logit.regression.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/logit.regression.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/logit.regression.py $file $SGE_TASK_ID combined
echo Run RF
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/random.forest.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/random.forest.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/random.forest.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/random.forest.py $file $SGE_TASK_ID combined
echo Run SVM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/support.vector.machine.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/support.vector.machine.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/support.vector.machine.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/support.vector.machine.py $file $SGE_TASK_ID combined
echo Run GBM
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/gradient.boosting.machine.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/gradient.boosting.machine.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/gradient.boosting.machine.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/gradient.boosting.machine.py $file $SGE_TASK_ID combined
echo Run MLP
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/multilayer.perceptron.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/multilayer.perceptron.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/multilayer.perceptron.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/multilayer.perceptron.py $file $SGE_TASK_ID combined

echo Plot combined PR curves
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/plot.all.PRcurves.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/plot.all.PRcurves.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/plot.all.PRcurves.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/plot.all.PRcurves.py $file $SGE_TASK_ID combined

echo voting classifier
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/voting.classifier.py $file $SGE_TASK_ID boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/voting.classifier.py $file $SGE_TASK_ID enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/voting.classifier.py $file $SGE_TASK_ID intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/SLE_paper/voting.classifier.py $file $SGE_TASK_ID combined

echo done split_$SGE_TASK_ID