## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -l tmp_requested=50G
#$ -pe smp 6
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.RF
#$ -t 1:12:1

conda activate Aim_3

cd /directflow/SCCGGroupShare/projects/lacgra/autoimmune.datasets/RA_SDY998

file=$(sed -n ${SGE_TASK_ID}p exp.matrix/file.list.txt)

python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/random.forest.py $file
