## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.SCENIC

conda activate Aim_1

# Set working directory
cd /directflow/SCCGGroupShare/projects/lacgra/autoimmune.datasets/pSS_GSE157278

#mkdir SCENIC

# Save Seurat file as loom
#Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/functions/export.loom.R

echo "Loom file created"

# Set file path
f_loom_path_scenic=pbmc.loom
f_pyscenic_output=SCENIC/pyscenic_output.loom
f_tfs=/directflow/SCCGGroupShare/projects/lacgra/SCENIC/allTFs_hg38.txt
f_db_names=(/directflow/SCCGGroupShare/projects/lacgra/SCENIC/cisTarget_databases/*feather)
f_motif_path=motifs-v10nr_clust-nr.hgnc-m0.001-o0.0.tbl

# Step 1
arboreto_with_multiprocessing.py \
    pbmc.loom \
    $f_tfs \
    --method grnboost2 \
    --output SCENIC/adj.tsv \
    --seed 777

echo "GRN created"

#Step 2 and 3:
pyscenic ctx SCENIC/adj.tsv \
    ${f_db_names[@]} \
    --annotations_fname $f_motif_path \
    --expression_mtx_fname $f_loom_path_scenic \
    --output SCENIC/reg.csv \
    --mask_dropouts

echo "CTX created"

# Step 4
pyscenic aucell \
    $f_loom_path_scenic \
    SCENIC/reg.csv \
    --output $f_pyscenic_output \
    --num_workers 0

echo "AUCELL created"