## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=20G
#$ -pe smp 8
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.ML.SLE.SHAP
#$ -t 1-43

conda activate Aim_3

# Set working directory
cd autoimmune.datasets/lupus_Chun

# Read in files
file=$(sed -n ${SGE_TASK_ID}p pseudobulk/file.list.txt)

echo $file

python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SHAP.py $file boruta
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SHAP.py $file enet
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SHAP.py $file intersection
python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_3/SHAP.py $file combined