## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=8G
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.SCimilarity

cd /directflow/SCCGGroupShare/projects/lacgra/SCimilarity

annotation_model=https://zenodo.org/record/8286452/files/annotation_model_v1.tar.gz?download=1
query_model=https://zenodo.org/record/8286452/files/query_model_v1.tar.gz?download=1

wget -O annotation_model.tar.gz $annotation_model

echo "Annotation model downloaded"

wget -O query_model.tar.gz $query_model

echo "Query model downloaded"