## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=5G
#$ -l tmp_requested=5G
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.GBM
#$ -t 1:3:1

conda activate Aim_3

cd /directflow/SCCGGroupShare/projects/lacgra/autoimmune.datasets/RA_SDY998

files=$(ls exp.matrix/*.RDS)

echo ${files[$SGE_TASK_ID]}

python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/qsub.scripts/test.py ${files[$SGE_TASK_ID]}
