## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=50G
#$ -pe smp 4
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.GCD-11

conda activate Aim_1

cd /directflow/SCCGGroupShare/projects/lacgra/autoimmune.datasets/pSS_GSE157278

#Rscript /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_1/GCD/prepare_GCD.R

dir_list=$(find GCD -type d | tail -n +2)
for i in $dir_list; do
  python2 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_1/GCD/count.py $i/control.gw
  python2 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_1/GCD/count.py $i/disease.gw
  python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/Python/Aim_1/GCD/network_comparison.py gcd11 $i 4
done
