## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=5G
#$ -l tmp_requested=5G
#$ -M lacgra@garvan.org.au
#$ -m ae
#$ -N out.test
#$ -t 1:3:1

conda activate Aim_3

cd /directflow/SCCGGroupShare/projects/lacgra/autoimmune.datasets/RA_SDY998

ls exp.matrix/*.RDS > test.txt
file=$(sed -n ${SGE_TASK_ID}p test.txt)

echo $file

python3 /directflow/SCCGGroupShare/projects/lacgra/PhD/qsub.scripts/test.py $file
